# Generated by Django 3.1.5 on 2021-01-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('user_name', models.CharField(max_length=30)),
                ('user_grade', models.IntegerField()),
                ('user_pn', models.CharField(max_length=11)),
                ('user_major', models.CharField(max_length=30)),
                ('user_q1', models.TextField()),
                ('user_q2', models.TextField()),
                ('user_q3', models.TextField()),
                ('user_q4', models.TextField()),
            ],
        ),
    ]
