# Generated by Django 3.1.5 on 2021-01-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likelion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_grade',
            field=models.IntegerField(null=True),
        ),
    ]
