# Generated by Django 3.1.6 on 2021-02-07 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('likelion', '0002_auto_20210128_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inform',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='informs', serialize=False, to='auth.user')),
                ('user_name', models.CharField(max_length=30)),
                ('user_grade', models.IntegerField(null=True)),
                ('user_pn', models.CharField(max_length=11)),
                ('user_major', models.CharField(max_length=30)),
                ('user_q1', models.TextField()),
                ('user_q2', models.TextField()),
                ('user_q3', models.TextField()),
                ('user_q4', models.TextField()),
                ('user_pass', models.IntegerField(default=2)),
                ('user_time', models.CharField(default='00:00', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
