# Generated by Django 3.1.6 on 2021-02-06 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likelion', '0002_auto_20210128_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_grade', models.IntegerField(null=True)),
                ('user_pn', models.CharField(max_length=11)),
                ('user_major', models.CharField(max_length=30)),
                ('user_q1', models.TextField()),
                ('user_q2', models.TextField()),
                ('user_q3', models.TextField()),
                ('user_q4', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
