# Generated by Django 3.1.5 on 2021-02-07 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likelion', '0003_auto_20210207_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inform',
            name='id',
        ),
        migrations.AddField(
            model_name='inform',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='informs', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
