# Generated by Django 3.1.6 on 2021-02-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likelion', '0003_user_user_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_time',
            field=models.CharField(default='00:00', max_length=20),
        ),
    ]
