# Generated by Django 3.1.6 on 2021-02-06 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likelion', '0003_auto_20210206_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inform',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informs', to=settings.AUTH_USER_MODEL),
        ),
    ]
