# Generated by Django 3.1.5 on 2021-02-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likelion', '0004_user_user_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=30),
        ),
    ]
