# Generated by Django 3.1.6 on 2021-02-06 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likelion', '0004_auto_20210206_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inform',
            name='id',
        ),
        migrations.AlterField(
            model_name='inform',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='informs', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
